#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
#saludar:
#    path: 
#      - /saludar/{nombre}
#      - /saludar
#    controller: App\Controller\DefaultController::saludar
  
